# Generated by Django 4.1.7 on 2023-04-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finconsult', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('CO', 'Consultant'), ('AD', 'Admin'), ('CL', 'Client')], default='CO', max_length=2),
        ),
    ]
