# Generated by Django 4.2.2 on 2023-06-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finconsult', '0004_profile_phone_alter_meeting_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
