# Generated by Django 4.2.2 on 2023-06-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finconsult', '0005_meeting_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meeting_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='bio',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='nc_birth_date',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='nc_name',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='nc_phone',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='newcommer',
        ),
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
